[package]
name = "image_serializer"
version = "0.1.0"
authors = ["Elijah Kim <reachelijah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
base64 = "0.13.0"
